### ISSUE TITLE
Add Unit testing

### ISSUE THREAD

**Issue by thamaraiselvam** [thamaraiselvam/mysql-import#2]
This library tested up to PHP 7.0.

Unit testing is required.

**Comment by antydemant** [comment]
@thamaraiselvam Can I take this one?

**Comment by thamaraiselvam** [comment]
Yes, you can 👍

**Comment by thamaraiselvam** [comment]
PR Merged

**Comment by marekfilip** [comment]
All done! Thanks for merge!

**Comment by thamaraiselvam** [comment]
you did great 👏🏼
