### ISSUE TITLE
Add Sheild io for travis build status

### ISSUE THREAD

**Issue by thamaraiselvam** [thamaraiselvam/mysql-import#9]
Update this image on Readme file

https://img.shields.io/travis/thamaraiselvam/mysql-import?style=for-the-badge

**Comment by Rantignac** [comment]
Hello @thamaraiselvam, 
you want to add just the image not the link of your travis ?

**Comment by thamaraiselvam** [comment]
Yes, the link is not required I guess because If it is a link where it will be pointed to.

**Comment by thamaraiselvam** [comment]
PR https://github.com/thamaraiselvam/mysql-import/pull/10
